name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build (${{ matrix.os }}/${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          # Задаем расширение .exe для Windows
          EXT=""
          if [ "${{ matrix.os }}" = "windows" ]; then
            EXT=".exe"
          fi
          
          # Имя результирующего файла, например: myapp-linux-amd64
          BINARY_NAME="dns-server-${{ matrix.os }}-${{ matrix.arch }}$EXT"
          
          # Сборка без отладочной информации для уменьшения размера (-ldflags="-s -w")
          go build -ldflags="-s -w" -o build/$BINARY_NAME .
          
          echo "Built $BINARY_NAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}-${{ matrix.arch }}
          path: build/*
          if-no-files-found: error
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Display downloaded files
        run: ls -R dist

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.sha }}
          name: "Nightly Build (${{ github.sha }})"
          body: "Auto release."
          files: dist/*
          prerelease: true